version: '3.3'
services:
    appserver:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: milk-appserver
        tty: true
        environment:
            - MYSQL_USER=milk
            - MYSQL_PASSWORD=milk
            - MYSQL_HOST=mysql
            - MYSQL_PORT=3306
            - MYSQL_DATABASE=milk
        ports:
            - 9090:9090
        volumes:
            - ./:/app
    mysql:
        image: mysql:5.7
        container_name: mysql
        command: mysqld --user=root
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=milk
            - MYSQL_USER=milk
            - MYSQL_PASSWORD=milk
            - MYSQL_DATABASE=milk
        volumes:
            - ./data:/data
            - ./database/sql:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
